/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model.impl;

import com.gdf.technical.bids.model.GDFTenderSubFPPMatDetails;
import com.gdf.technical.bids.model.GDFTenderSubFPPMatDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GDFTenderSubFPPMatDetails service. Represents a row in the &quot;PRT_GDFTender_SubFPPMat_Det&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GDFTenderSubFPPMatDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GDFTenderSubFPPMatDetailsImpl}.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderSubFPPMatDetailsImpl
 * @generated
 */
public class GDFTenderSubFPPMatDetailsModelImpl
	extends BaseModelImpl<GDFTenderSubFPPMatDetails>
	implements GDFTenderSubFPPMatDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gdf tender sub fpp mat details model instance should use the <code>GDFTenderSubFPPMatDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRT_GDFTender_SubFPPMat_Det";

	public static final Object[][] TABLE_COLUMNS = {
		{"GDF_Tender_Item_Mat_Ref_Id", Types.BIGINT},
		{"GDF_Tender_Schedule_Number", Types.BIGINT},
		{"GDF_Generic_Code", Types.VARCHAR},
		{"GDF_Tender_Reference_Number", Types.VARCHAR},
		{"Dosage_Form", Types.VARCHAR}, {"No_Prim_Package_Units", Types.BIGINT},
		{"No_Sec_Package_Units", Types.BIGINT},
		{"Gdf_Fpp_Mart_Appr_Status", Types.VARCHAR},
		{"FPP_Selected_Status", Types.BOOLEAN}, {"FPP_Market_Id", Types.BIGINT},
		{"GDF_Tender_Item_Ref_Id", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("GDF_Tender_Item_Mat_Ref_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Schedule_Number", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Generic_Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Reference_Number", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Dosage_Form", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("No_Prim_Package_Units", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("No_Sec_Package_Units", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Gdf_Fpp_Mart_Appr_Status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FPP_Selected_Status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("FPP_Market_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Item_Ref_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRT_GDFTender_SubFPPMat_Det (GDF_Tender_Item_Mat_Ref_Id LONG not null primary key IDENTITY,GDF_Tender_Schedule_Number LONG,GDF_Generic_Code VARCHAR(100) null,GDF_Tender_Reference_Number VARCHAR(100) null,Dosage_Form VARCHAR(100) null,No_Prim_Package_Units LONG,No_Sec_Package_Units LONG,Gdf_Fpp_Mart_Appr_Status VARCHAR(100) null,FPP_Selected_Status BOOLEAN,FPP_Market_Id LONG,GDF_Tender_Item_Ref_Id LONG,userId LONG,userName VARCHAR(100) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table PRT_GDFTender_SubFPPMat_Det";

	public static final String ORDER_BY_JPQL =
		" ORDER BY gdfTenderSubFPPMatDetails.tenderItemMatRefID ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRT_GDFTender_SubFPPMat_Det.GDF_Tender_Item_Mat_Ref_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long FPPMARKETID_COLUMN_BITMASK = 1L;

	public static final long FPPSELECTEDSTATUS_COLUMN_BITMASK = 2L;

	public static final long GDFGENERICCODE_COLUMN_BITMASK = 4L;

	public static final long SCHEDULENUMBER_COLUMN_BITMASK = 8L;

	public static final long TENDERITEMMATREFID_COLUMN_BITMASK = 16L;

	public static final long TENDERREFERENCENUMBER_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public GDFTenderSubFPPMatDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tenderItemMatRefID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTenderItemMatRefID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tenderItemMatRefID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GDFTenderSubFPPMatDetails.class;
	}

	@Override
	public String getModelClassName() {
		return GDFTenderSubFPPMatDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GDFTenderSubFPPMatDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GDFTenderSubFPPMatDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubFPPMatDetails, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GDFTenderSubFPPMatDetails)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GDFTenderSubFPPMatDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GDFTenderSubFPPMatDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GDFTenderSubFPPMatDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GDFTenderSubFPPMatDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GDFTenderSubFPPMatDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GDFTenderSubFPPMatDetails>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GDFTenderSubFPPMatDetails.class.getClassLoader(),
			GDFTenderSubFPPMatDetails.class, ModelWrapper.class);

		try {
			Constructor<GDFTenderSubFPPMatDetails> constructor =
				(Constructor<GDFTenderSubFPPMatDetails>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<GDFTenderSubFPPMatDetails, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<GDFTenderSubFPPMatDetails, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<GDFTenderSubFPPMatDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<GDFTenderSubFPPMatDetails, Object>>();
		Map<String, BiConsumer<GDFTenderSubFPPMatDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<GDFTenderSubFPPMatDetails, ?>>();

		attributeGetterFunctions.put(
			"tenderItemMatRefID",
			GDFTenderSubFPPMatDetails::getTenderItemMatRefID);
		attributeSetterBiConsumers.put(
			"tenderItemMatRefID",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setTenderItemMatRefID);
		attributeGetterFunctions.put(
			"scheduleNumber", GDFTenderSubFPPMatDetails::getScheduleNumber);
		attributeSetterBiConsumers.put(
			"scheduleNumber",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setScheduleNumber);
		attributeGetterFunctions.put(
			"gdfGenericCode", GDFTenderSubFPPMatDetails::getGdfGenericCode);
		attributeSetterBiConsumers.put(
			"gdfGenericCode",
			(BiConsumer<GDFTenderSubFPPMatDetails, String>)
				GDFTenderSubFPPMatDetails::setGdfGenericCode);
		attributeGetterFunctions.put(
			"tenderReferenceNumber",
			GDFTenderSubFPPMatDetails::getTenderReferenceNumber);
		attributeSetterBiConsumers.put(
			"tenderReferenceNumber",
			(BiConsumer<GDFTenderSubFPPMatDetails, String>)
				GDFTenderSubFPPMatDetails::setTenderReferenceNumber);
		attributeGetterFunctions.put(
			"dosageForm", GDFTenderSubFPPMatDetails::getDosageForm);
		attributeSetterBiConsumers.put(
			"dosageForm",
			(BiConsumer<GDFTenderSubFPPMatDetails, String>)
				GDFTenderSubFPPMatDetails::setDosageForm);
		attributeGetterFunctions.put(
			"noPrimPackageUnits",
			GDFTenderSubFPPMatDetails::getNoPrimPackageUnits);
		attributeSetterBiConsumers.put(
			"noPrimPackageUnits",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setNoPrimPackageUnits);
		attributeGetterFunctions.put(
			"noSecPackageUnits",
			GDFTenderSubFPPMatDetails::getNoSecPackageUnits);
		attributeSetterBiConsumers.put(
			"noSecPackageUnits",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setNoSecPackageUnits);
		attributeGetterFunctions.put(
			"gdfFppMartApprStatus",
			GDFTenderSubFPPMatDetails::getGdfFppMartApprStatus);
		attributeSetterBiConsumers.put(
			"gdfFppMartApprStatus",
			(BiConsumer<GDFTenderSubFPPMatDetails, String>)
				GDFTenderSubFPPMatDetails::setGdfFppMartApprStatus);
		attributeGetterFunctions.put(
			"fppSelectedStatus",
			GDFTenderSubFPPMatDetails::getFppSelectedStatus);
		attributeSetterBiConsumers.put(
			"fppSelectedStatus",
			(BiConsumer<GDFTenderSubFPPMatDetails, Boolean>)
				GDFTenderSubFPPMatDetails::setFppSelectedStatus);
		attributeGetterFunctions.put(
			"fppMarketID", GDFTenderSubFPPMatDetails::getFppMarketID);
		attributeSetterBiConsumers.put(
			"fppMarketID",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setFppMarketID);
		attributeGetterFunctions.put(
			"tenderItemRefID", GDFTenderSubFPPMatDetails::getTenderItemRefID);
		attributeSetterBiConsumers.put(
			"tenderItemRefID",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setTenderItemRefID);
		attributeGetterFunctions.put(
			"userId", GDFTenderSubFPPMatDetails::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GDFTenderSubFPPMatDetails, Long>)
				GDFTenderSubFPPMatDetails::setUserId);
		attributeGetterFunctions.put(
			"userName", GDFTenderSubFPPMatDetails::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<GDFTenderSubFPPMatDetails, String>)
				GDFTenderSubFPPMatDetails::setUserName);
		attributeGetterFunctions.put(
			"createDate", GDFTenderSubFPPMatDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GDFTenderSubFPPMatDetails, Date>)
				GDFTenderSubFPPMatDetails::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GDFTenderSubFPPMatDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GDFTenderSubFPPMatDetails, Date>)
				GDFTenderSubFPPMatDetails::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTenderItemMatRefID() {
		return _tenderItemMatRefID;
	}

	@Override
	public void setTenderItemMatRefID(long tenderItemMatRefID) {
		_columnBitmask |= TENDERITEMMATREFID_COLUMN_BITMASK;

		if (!_setOriginalTenderItemMatRefID) {
			_setOriginalTenderItemMatRefID = true;

			_originalTenderItemMatRefID = _tenderItemMatRefID;
		}

		_tenderItemMatRefID = tenderItemMatRefID;
	}

	public long getOriginalTenderItemMatRefID() {
		return _originalTenderItemMatRefID;
	}

	@Override
	public long getScheduleNumber() {
		return _scheduleNumber;
	}

	@Override
	public void setScheduleNumber(long scheduleNumber) {
		_columnBitmask |= SCHEDULENUMBER_COLUMN_BITMASK;

		if (!_setOriginalScheduleNumber) {
			_setOriginalScheduleNumber = true;

			_originalScheduleNumber = _scheduleNumber;
		}

		_scheduleNumber = scheduleNumber;
	}

	public long getOriginalScheduleNumber() {
		return _originalScheduleNumber;
	}

	@Override
	public String getGdfGenericCode() {
		if (_gdfGenericCode == null) {
			return "";
		}
		else {
			return _gdfGenericCode;
		}
	}

	@Override
	public void setGdfGenericCode(String gdfGenericCode) {
		_columnBitmask |= GDFGENERICCODE_COLUMN_BITMASK;

		if (_originalGdfGenericCode == null) {
			_originalGdfGenericCode = _gdfGenericCode;
		}

		_gdfGenericCode = gdfGenericCode;
	}

	public String getOriginalGdfGenericCode() {
		return GetterUtil.getString(_originalGdfGenericCode);
	}

	@Override
	public String getTenderReferenceNumber() {
		if (_tenderReferenceNumber == null) {
			return "";
		}
		else {
			return _tenderReferenceNumber;
		}
	}

	@Override
	public void setTenderReferenceNumber(String tenderReferenceNumber) {
		_columnBitmask |= TENDERREFERENCENUMBER_COLUMN_BITMASK;

		if (_originalTenderReferenceNumber == null) {
			_originalTenderReferenceNumber = _tenderReferenceNumber;
		}

		_tenderReferenceNumber = tenderReferenceNumber;
	}

	public String getOriginalTenderReferenceNumber() {
		return GetterUtil.getString(_originalTenderReferenceNumber);
	}

	@Override
	public String getDosageForm() {
		if (_dosageForm == null) {
			return "";
		}
		else {
			return _dosageForm;
		}
	}

	@Override
	public void setDosageForm(String dosageForm) {
		_dosageForm = dosageForm;
	}

	@Override
	public long getNoPrimPackageUnits() {
		return _noPrimPackageUnits;
	}

	@Override
	public void setNoPrimPackageUnits(long noPrimPackageUnits) {
		_noPrimPackageUnits = noPrimPackageUnits;
	}

	@Override
	public long getNoSecPackageUnits() {
		return _noSecPackageUnits;
	}

	@Override
	public void setNoSecPackageUnits(long noSecPackageUnits) {
		_noSecPackageUnits = noSecPackageUnits;
	}

	@Override
	public String getGdfFppMartApprStatus() {
		if (_gdfFppMartApprStatus == null) {
			return "";
		}
		else {
			return _gdfFppMartApprStatus;
		}
	}

	@Override
	public void setGdfFppMartApprStatus(String gdfFppMartApprStatus) {
		_gdfFppMartApprStatus = gdfFppMartApprStatus;
	}

	@Override
	public boolean getFppSelectedStatus() {
		return _fppSelectedStatus;
	}

	@Override
	public boolean isFppSelectedStatus() {
		return _fppSelectedStatus;
	}

	@Override
	public void setFppSelectedStatus(boolean fppSelectedStatus) {
		_columnBitmask |= FPPSELECTEDSTATUS_COLUMN_BITMASK;

		if (!_setOriginalFppSelectedStatus) {
			_setOriginalFppSelectedStatus = true;

			_originalFppSelectedStatus = _fppSelectedStatus;
		}

		_fppSelectedStatus = fppSelectedStatus;
	}

	public boolean getOriginalFppSelectedStatus() {
		return _originalFppSelectedStatus;
	}

	@Override
	public long getFppMarketID() {
		return _fppMarketID;
	}

	@Override
	public void setFppMarketID(long fppMarketID) {
		_columnBitmask |= FPPMARKETID_COLUMN_BITMASK;

		if (!_setOriginalFppMarketID) {
			_setOriginalFppMarketID = true;

			_originalFppMarketID = _fppMarketID;
		}

		_fppMarketID = fppMarketID;
	}

	public long getOriginalFppMarketID() {
		return _originalFppMarketID;
	}

	@Override
	public long getTenderItemRefID() {
		return _tenderItemRefID;
	}

	@Override
	public void setTenderItemRefID(long tenderItemRefID) {
		_tenderItemRefID = tenderItemRefID;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, GDFTenderSubFPPMatDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GDFTenderSubFPPMatDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GDFTenderSubFPPMatDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GDFTenderSubFPPMatDetailsImpl gdfTenderSubFPPMatDetailsImpl =
			new GDFTenderSubFPPMatDetailsImpl();

		gdfTenderSubFPPMatDetailsImpl.setTenderItemMatRefID(
			getTenderItemMatRefID());
		gdfTenderSubFPPMatDetailsImpl.setScheduleNumber(getScheduleNumber());
		gdfTenderSubFPPMatDetailsImpl.setGdfGenericCode(getGdfGenericCode());
		gdfTenderSubFPPMatDetailsImpl.setTenderReferenceNumber(
			getTenderReferenceNumber());
		gdfTenderSubFPPMatDetailsImpl.setDosageForm(getDosageForm());
		gdfTenderSubFPPMatDetailsImpl.setNoPrimPackageUnits(
			getNoPrimPackageUnits());
		gdfTenderSubFPPMatDetailsImpl.setNoSecPackageUnits(
			getNoSecPackageUnits());
		gdfTenderSubFPPMatDetailsImpl.setGdfFppMartApprStatus(
			getGdfFppMartApprStatus());
		gdfTenderSubFPPMatDetailsImpl.setFppSelectedStatus(
			isFppSelectedStatus());
		gdfTenderSubFPPMatDetailsImpl.setFppMarketID(getFppMarketID());
		gdfTenderSubFPPMatDetailsImpl.setTenderItemRefID(getTenderItemRefID());
		gdfTenderSubFPPMatDetailsImpl.setUserId(getUserId());
		gdfTenderSubFPPMatDetailsImpl.setUserName(getUserName());
		gdfTenderSubFPPMatDetailsImpl.setCreateDate(getCreateDate());
		gdfTenderSubFPPMatDetailsImpl.setModifiedDate(getModifiedDate());

		gdfTenderSubFPPMatDetailsImpl.resetOriginalValues();

		return gdfTenderSubFPPMatDetailsImpl;
	}

	@Override
	public int compareTo(GDFTenderSubFPPMatDetails gdfTenderSubFPPMatDetails) {
		long primaryKey = gdfTenderSubFPPMatDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GDFTenderSubFPPMatDetails)) {
			return false;
		}

		GDFTenderSubFPPMatDetails gdfTenderSubFPPMatDetails =
			(GDFTenderSubFPPMatDetails)obj;

		long primaryKey = gdfTenderSubFPPMatDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GDFTenderSubFPPMatDetailsModelImpl gdfTenderSubFPPMatDetailsModelImpl =
			this;

		gdfTenderSubFPPMatDetailsModelImpl._originalTenderItemMatRefID =
			gdfTenderSubFPPMatDetailsModelImpl._tenderItemMatRefID;

		gdfTenderSubFPPMatDetailsModelImpl._setOriginalTenderItemMatRefID =
			false;

		gdfTenderSubFPPMatDetailsModelImpl._originalScheduleNumber =
			gdfTenderSubFPPMatDetailsModelImpl._scheduleNumber;

		gdfTenderSubFPPMatDetailsModelImpl._setOriginalScheduleNumber = false;

		gdfTenderSubFPPMatDetailsModelImpl._originalGdfGenericCode =
			gdfTenderSubFPPMatDetailsModelImpl._gdfGenericCode;

		gdfTenderSubFPPMatDetailsModelImpl._originalTenderReferenceNumber =
			gdfTenderSubFPPMatDetailsModelImpl._tenderReferenceNumber;

		gdfTenderSubFPPMatDetailsModelImpl._originalFppSelectedStatus =
			gdfTenderSubFPPMatDetailsModelImpl._fppSelectedStatus;

		gdfTenderSubFPPMatDetailsModelImpl._setOriginalFppSelectedStatus =
			false;

		gdfTenderSubFPPMatDetailsModelImpl._originalFppMarketID =
			gdfTenderSubFPPMatDetailsModelImpl._fppMarketID;

		gdfTenderSubFPPMatDetailsModelImpl._setOriginalFppMarketID = false;

		gdfTenderSubFPPMatDetailsModelImpl._originalUserId =
			gdfTenderSubFPPMatDetailsModelImpl._userId;

		gdfTenderSubFPPMatDetailsModelImpl._setOriginalUserId = false;

		gdfTenderSubFPPMatDetailsModelImpl._setModifiedDate = false;

		gdfTenderSubFPPMatDetailsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GDFTenderSubFPPMatDetails> toCacheModel() {
		GDFTenderSubFPPMatDetailsCacheModel
			gdfTenderSubFPPMatDetailsCacheModel =
				new GDFTenderSubFPPMatDetailsCacheModel();

		gdfTenderSubFPPMatDetailsCacheModel.tenderItemMatRefID =
			getTenderItemMatRefID();

		gdfTenderSubFPPMatDetailsCacheModel.scheduleNumber =
			getScheduleNumber();

		gdfTenderSubFPPMatDetailsCacheModel.gdfGenericCode =
			getGdfGenericCode();

		String gdfGenericCode =
			gdfTenderSubFPPMatDetailsCacheModel.gdfGenericCode;

		if ((gdfGenericCode != null) && (gdfGenericCode.length() == 0)) {
			gdfTenderSubFPPMatDetailsCacheModel.gdfGenericCode = null;
		}

		gdfTenderSubFPPMatDetailsCacheModel.tenderReferenceNumber =
			getTenderReferenceNumber();

		String tenderReferenceNumber =
			gdfTenderSubFPPMatDetailsCacheModel.tenderReferenceNumber;

		if ((tenderReferenceNumber != null) &&
			(tenderReferenceNumber.length() == 0)) {

			gdfTenderSubFPPMatDetailsCacheModel.tenderReferenceNumber = null;
		}

		gdfTenderSubFPPMatDetailsCacheModel.dosageForm = getDosageForm();

		String dosageForm = gdfTenderSubFPPMatDetailsCacheModel.dosageForm;

		if ((dosageForm != null) && (dosageForm.length() == 0)) {
			gdfTenderSubFPPMatDetailsCacheModel.dosageForm = null;
		}

		gdfTenderSubFPPMatDetailsCacheModel.noPrimPackageUnits =
			getNoPrimPackageUnits();

		gdfTenderSubFPPMatDetailsCacheModel.noSecPackageUnits =
			getNoSecPackageUnits();

		gdfTenderSubFPPMatDetailsCacheModel.gdfFppMartApprStatus =
			getGdfFppMartApprStatus();

		String gdfFppMartApprStatus =
			gdfTenderSubFPPMatDetailsCacheModel.gdfFppMartApprStatus;

		if ((gdfFppMartApprStatus != null) &&
			(gdfFppMartApprStatus.length() == 0)) {

			gdfTenderSubFPPMatDetailsCacheModel.gdfFppMartApprStatus = null;
		}

		gdfTenderSubFPPMatDetailsCacheModel.fppSelectedStatus =
			isFppSelectedStatus();

		gdfTenderSubFPPMatDetailsCacheModel.fppMarketID = getFppMarketID();

		gdfTenderSubFPPMatDetailsCacheModel.tenderItemRefID =
			getTenderItemRefID();

		gdfTenderSubFPPMatDetailsCacheModel.userId = getUserId();

		gdfTenderSubFPPMatDetailsCacheModel.userName = getUserName();

		String userName = gdfTenderSubFPPMatDetailsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			gdfTenderSubFPPMatDetailsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			gdfTenderSubFPPMatDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			gdfTenderSubFPPMatDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			gdfTenderSubFPPMatDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			gdfTenderSubFPPMatDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return gdfTenderSubFPPMatDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GDFTenderSubFPPMatDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GDFTenderSubFPPMatDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubFPPMatDetails, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((GDFTenderSubFPPMatDetails)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GDFTenderSubFPPMatDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GDFTenderSubFPPMatDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubFPPMatDetails, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((GDFTenderSubFPPMatDetails)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, GDFTenderSubFPPMatDetails>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _tenderItemMatRefID;
	private long _originalTenderItemMatRefID;
	private boolean _setOriginalTenderItemMatRefID;
	private long _scheduleNumber;
	private long _originalScheduleNumber;
	private boolean _setOriginalScheduleNumber;
	private String _gdfGenericCode;
	private String _originalGdfGenericCode;
	private String _tenderReferenceNumber;
	private String _originalTenderReferenceNumber;
	private String _dosageForm;
	private long _noPrimPackageUnits;
	private long _noSecPackageUnits;
	private String _gdfFppMartApprStatus;
	private boolean _fppSelectedStatus;
	private boolean _originalFppSelectedStatus;
	private boolean _setOriginalFppSelectedStatus;
	private long _fppMarketID;
	private long _originalFppMarketID;
	private boolean _setOriginalFppMarketID;
	private long _tenderItemRefID;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private GDFTenderSubFPPMatDetails _escapedModel;

}