/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model.impl;

import com.gdf.technical.bids.model.GDFTenderSubSchedDetails;
import com.gdf.technical.bids.model.GDFTenderSubSchedDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GDFTenderSubSchedDetails service. Represents a row in the &quot;PRT_GDFTender_SubSched_Det&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GDFTenderSubSchedDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GDFTenderSubSchedDetailsImpl}.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderSubSchedDetailsImpl
 * @generated
 */
public class GDFTenderSubSchedDetailsModelImpl
	extends BaseModelImpl<GDFTenderSubSchedDetails>
	implements GDFTenderSubSchedDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gdf tender sub sched details model instance should use the <code>GDFTenderSubSchedDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRT_GDFTender_SubSched_Det";

	public static final Object[][] TABLE_COLUMNS = {
		{"GDF_Tender_Sub_Sched_Ref_Id", Types.BIGINT},
		{"GDF_Tender_Item_Num", Types.BIGINT},
		{"GDF_Tender_Schedule_Number", Types.BIGINT},
		{"GDF_Generic_Code", Types.VARCHAR},
		{"GDF_Tender_Reference_Number", Types.VARCHAR},
		{"GDF_Tender_Schedule_Name", Types.VARCHAR},
		{"GDF_PatientTarget", Types.VARCHAR},
		{"GDF_Tender_Item_Ref_Id", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("GDF_Tender_Sub_Sched_Ref_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Item_Num", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Schedule_Number", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("GDF_Generic_Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Reference_Number", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Schedule_Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GDF_PatientTarget", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GDF_Tender_Item_Ref_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRT_GDFTender_SubSched_Det (GDF_Tender_Sub_Sched_Ref_Id LONG not null primary key IDENTITY,GDF_Tender_Item_Num LONG,GDF_Tender_Schedule_Number LONG,GDF_Generic_Code VARCHAR(75) null,GDF_Tender_Reference_Number VARCHAR(75) null,GDF_Tender_Schedule_Name VARCHAR(75) null,GDF_PatientTarget VARCHAR(75) null,GDF_Tender_Item_Ref_Id LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table PRT_GDFTender_SubSched_Det";

	public static final String ORDER_BY_JPQL =
		" ORDER BY gdfTenderSubSchedDetails.tenderSubSchedRefID ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRT_GDFTender_SubSched_Det.GDF_Tender_Sub_Sched_Ref_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GDFGENERICCODE_COLUMN_BITMASK = 1L;

	public static final long SCHEDULENUMBER_COLUMN_BITMASK = 2L;

	public static final long TENDERITEMNUMBER_COLUMN_BITMASK = 4L;

	public static final long TENDERITEMREFID_COLUMN_BITMASK = 8L;

	public static final long TENDERREFERENCENUMBER_COLUMN_BITMASK = 16L;

	public static final long TENDERSUBSCHEDREFID_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public GDFTenderSubSchedDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tenderSubSchedRefID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTenderSubSchedRefID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tenderSubSchedRefID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GDFTenderSubSchedDetails.class;
	}

	@Override
	public String getModelClassName() {
		return GDFTenderSubSchedDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GDFTenderSubSchedDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GDFTenderSubSchedDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubSchedDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GDFTenderSubSchedDetails)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GDFTenderSubSchedDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GDFTenderSubSchedDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GDFTenderSubSchedDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GDFTenderSubSchedDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GDFTenderSubSchedDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GDFTenderSubSchedDetails>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GDFTenderSubSchedDetails.class.getClassLoader(),
			GDFTenderSubSchedDetails.class, ModelWrapper.class);

		try {
			Constructor<GDFTenderSubSchedDetails> constructor =
				(Constructor<GDFTenderSubSchedDetails>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GDFTenderSubSchedDetails, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<GDFTenderSubSchedDetails, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<GDFTenderSubSchedDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<GDFTenderSubSchedDetails, Object>>();
		Map<String, BiConsumer<GDFTenderSubSchedDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<GDFTenderSubSchedDetails, ?>>();

		attributeGetterFunctions.put(
			"tenderSubSchedRefID",
			GDFTenderSubSchedDetails::getTenderSubSchedRefID);
		attributeSetterBiConsumers.put(
			"tenderSubSchedRefID",
			(BiConsumer<GDFTenderSubSchedDetails, Long>)
				GDFTenderSubSchedDetails::setTenderSubSchedRefID);
		attributeGetterFunctions.put(
			"tenderItemNumber", GDFTenderSubSchedDetails::getTenderItemNumber);
		attributeSetterBiConsumers.put(
			"tenderItemNumber",
			(BiConsumer<GDFTenderSubSchedDetails, Long>)
				GDFTenderSubSchedDetails::setTenderItemNumber);
		attributeGetterFunctions.put(
			"scheduleNumber", GDFTenderSubSchedDetails::getScheduleNumber);
		attributeSetterBiConsumers.put(
			"scheduleNumber",
			(BiConsumer<GDFTenderSubSchedDetails, Long>)
				GDFTenderSubSchedDetails::setScheduleNumber);
		attributeGetterFunctions.put(
			"gdfGenericCode", GDFTenderSubSchedDetails::getGdfGenericCode);
		attributeSetterBiConsumers.put(
			"gdfGenericCode",
			(BiConsumer<GDFTenderSubSchedDetails, String>)
				GDFTenderSubSchedDetails::setGdfGenericCode);
		attributeGetterFunctions.put(
			"tenderReferenceNumber",
			GDFTenderSubSchedDetails::getTenderReferenceNumber);
		attributeSetterBiConsumers.put(
			"tenderReferenceNumber",
			(BiConsumer<GDFTenderSubSchedDetails, String>)
				GDFTenderSubSchedDetails::setTenderReferenceNumber);
		attributeGetterFunctions.put(
			"scheduleName", GDFTenderSubSchedDetails::getScheduleName);
		attributeSetterBiConsumers.put(
			"scheduleName",
			(BiConsumer<GDFTenderSubSchedDetails, String>)
				GDFTenderSubSchedDetails::setScheduleName);
		attributeGetterFunctions.put(
			"patientTarget", GDFTenderSubSchedDetails::getPatientTarget);
		attributeSetterBiConsumers.put(
			"patientTarget",
			(BiConsumer<GDFTenderSubSchedDetails, String>)
				GDFTenderSubSchedDetails::setPatientTarget);
		attributeGetterFunctions.put(
			"tenderItemRefID", GDFTenderSubSchedDetails::getTenderItemRefID);
		attributeSetterBiConsumers.put(
			"tenderItemRefID",
			(BiConsumer<GDFTenderSubSchedDetails, Long>)
				GDFTenderSubSchedDetails::setTenderItemRefID);
		attributeGetterFunctions.put(
			"userId", GDFTenderSubSchedDetails::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GDFTenderSubSchedDetails, Long>)
				GDFTenderSubSchedDetails::setUserId);
		attributeGetterFunctions.put(
			"userName", GDFTenderSubSchedDetails::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<GDFTenderSubSchedDetails, String>)
				GDFTenderSubSchedDetails::setUserName);
		attributeGetterFunctions.put(
			"createDate", GDFTenderSubSchedDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GDFTenderSubSchedDetails, Date>)
				GDFTenderSubSchedDetails::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GDFTenderSubSchedDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GDFTenderSubSchedDetails, Date>)
				GDFTenderSubSchedDetails::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTenderSubSchedRefID() {
		return _tenderSubSchedRefID;
	}

	@Override
	public void setTenderSubSchedRefID(long tenderSubSchedRefID) {
		_columnBitmask |= TENDERSUBSCHEDREFID_COLUMN_BITMASK;

		if (!_setOriginalTenderSubSchedRefID) {
			_setOriginalTenderSubSchedRefID = true;

			_originalTenderSubSchedRefID = _tenderSubSchedRefID;
		}

		_tenderSubSchedRefID = tenderSubSchedRefID;
	}

	public long getOriginalTenderSubSchedRefID() {
		return _originalTenderSubSchedRefID;
	}

	@Override
	public long getTenderItemNumber() {
		return _tenderItemNumber;
	}

	@Override
	public void setTenderItemNumber(long tenderItemNumber) {
		_columnBitmask |= TENDERITEMNUMBER_COLUMN_BITMASK;

		if (!_setOriginalTenderItemNumber) {
			_setOriginalTenderItemNumber = true;

			_originalTenderItemNumber = _tenderItemNumber;
		}

		_tenderItemNumber = tenderItemNumber;
	}

	public long getOriginalTenderItemNumber() {
		return _originalTenderItemNumber;
	}

	@Override
	public long getScheduleNumber() {
		return _scheduleNumber;
	}

	@Override
	public void setScheduleNumber(long scheduleNumber) {
		_columnBitmask |= SCHEDULENUMBER_COLUMN_BITMASK;

		if (!_setOriginalScheduleNumber) {
			_setOriginalScheduleNumber = true;

			_originalScheduleNumber = _scheduleNumber;
		}

		_scheduleNumber = scheduleNumber;
	}

	public long getOriginalScheduleNumber() {
		return _originalScheduleNumber;
	}

	@Override
	public String getGdfGenericCode() {
		if (_gdfGenericCode == null) {
			return "";
		}
		else {
			return _gdfGenericCode;
		}
	}

	@Override
	public void setGdfGenericCode(String gdfGenericCode) {
		_columnBitmask |= GDFGENERICCODE_COLUMN_BITMASK;

		if (_originalGdfGenericCode == null) {
			_originalGdfGenericCode = _gdfGenericCode;
		}

		_gdfGenericCode = gdfGenericCode;
	}

	public String getOriginalGdfGenericCode() {
		return GetterUtil.getString(_originalGdfGenericCode);
	}

	@Override
	public String getTenderReferenceNumber() {
		if (_tenderReferenceNumber == null) {
			return "";
		}
		else {
			return _tenderReferenceNumber;
		}
	}

	@Override
	public void setTenderReferenceNumber(String tenderReferenceNumber) {
		_columnBitmask |= TENDERREFERENCENUMBER_COLUMN_BITMASK;

		if (_originalTenderReferenceNumber == null) {
			_originalTenderReferenceNumber = _tenderReferenceNumber;
		}

		_tenderReferenceNumber = tenderReferenceNumber;
	}

	public String getOriginalTenderReferenceNumber() {
		return GetterUtil.getString(_originalTenderReferenceNumber);
	}

	@Override
	public String getScheduleName() {
		if (_scheduleName == null) {
			return "";
		}
		else {
			return _scheduleName;
		}
	}

	@Override
	public void setScheduleName(String scheduleName) {
		_scheduleName = scheduleName;
	}

	@Override
	public String getPatientTarget() {
		if (_patientTarget == null) {
			return "";
		}
		else {
			return _patientTarget;
		}
	}

	@Override
	public void setPatientTarget(String patientTarget) {
		_patientTarget = patientTarget;
	}

	@Override
	public long getTenderItemRefID() {
		return _tenderItemRefID;
	}

	@Override
	public void setTenderItemRefID(long tenderItemRefID) {
		_columnBitmask |= TENDERITEMREFID_COLUMN_BITMASK;

		if (!_setOriginalTenderItemRefID) {
			_setOriginalTenderItemRefID = true;

			_originalTenderItemRefID = _tenderItemRefID;
		}

		_tenderItemRefID = tenderItemRefID;
	}

	public long getOriginalTenderItemRefID() {
		return _originalTenderItemRefID;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, GDFTenderSubSchedDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GDFTenderSubSchedDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GDFTenderSubSchedDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GDFTenderSubSchedDetailsImpl gdfTenderSubSchedDetailsImpl =
			new GDFTenderSubSchedDetailsImpl();

		gdfTenderSubSchedDetailsImpl.setTenderSubSchedRefID(
			getTenderSubSchedRefID());
		gdfTenderSubSchedDetailsImpl.setTenderItemNumber(getTenderItemNumber());
		gdfTenderSubSchedDetailsImpl.setScheduleNumber(getScheduleNumber());
		gdfTenderSubSchedDetailsImpl.setGdfGenericCode(getGdfGenericCode());
		gdfTenderSubSchedDetailsImpl.setTenderReferenceNumber(
			getTenderReferenceNumber());
		gdfTenderSubSchedDetailsImpl.setScheduleName(getScheduleName());
		gdfTenderSubSchedDetailsImpl.setPatientTarget(getPatientTarget());
		gdfTenderSubSchedDetailsImpl.setTenderItemRefID(getTenderItemRefID());
		gdfTenderSubSchedDetailsImpl.setUserId(getUserId());
		gdfTenderSubSchedDetailsImpl.setUserName(getUserName());
		gdfTenderSubSchedDetailsImpl.setCreateDate(getCreateDate());
		gdfTenderSubSchedDetailsImpl.setModifiedDate(getModifiedDate());

		gdfTenderSubSchedDetailsImpl.resetOriginalValues();

		return gdfTenderSubSchedDetailsImpl;
	}

	@Override
	public int compareTo(GDFTenderSubSchedDetails gdfTenderSubSchedDetails) {
		long primaryKey = gdfTenderSubSchedDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GDFTenderSubSchedDetails)) {
			return false;
		}

		GDFTenderSubSchedDetails gdfTenderSubSchedDetails =
			(GDFTenderSubSchedDetails)obj;

		long primaryKey = gdfTenderSubSchedDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GDFTenderSubSchedDetailsModelImpl gdfTenderSubSchedDetailsModelImpl =
			this;

		gdfTenderSubSchedDetailsModelImpl._originalTenderSubSchedRefID =
			gdfTenderSubSchedDetailsModelImpl._tenderSubSchedRefID;

		gdfTenderSubSchedDetailsModelImpl._setOriginalTenderSubSchedRefID =
			false;

		gdfTenderSubSchedDetailsModelImpl._originalTenderItemNumber =
			gdfTenderSubSchedDetailsModelImpl._tenderItemNumber;

		gdfTenderSubSchedDetailsModelImpl._setOriginalTenderItemNumber = false;

		gdfTenderSubSchedDetailsModelImpl._originalScheduleNumber =
			gdfTenderSubSchedDetailsModelImpl._scheduleNumber;

		gdfTenderSubSchedDetailsModelImpl._setOriginalScheduleNumber = false;

		gdfTenderSubSchedDetailsModelImpl._originalGdfGenericCode =
			gdfTenderSubSchedDetailsModelImpl._gdfGenericCode;

		gdfTenderSubSchedDetailsModelImpl._originalTenderReferenceNumber =
			gdfTenderSubSchedDetailsModelImpl._tenderReferenceNumber;

		gdfTenderSubSchedDetailsModelImpl._originalTenderItemRefID =
			gdfTenderSubSchedDetailsModelImpl._tenderItemRefID;

		gdfTenderSubSchedDetailsModelImpl._setOriginalTenderItemRefID = false;

		gdfTenderSubSchedDetailsModelImpl._setModifiedDate = false;

		gdfTenderSubSchedDetailsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GDFTenderSubSchedDetails> toCacheModel() {
		GDFTenderSubSchedDetailsCacheModel gdfTenderSubSchedDetailsCacheModel =
			new GDFTenderSubSchedDetailsCacheModel();

		gdfTenderSubSchedDetailsCacheModel.tenderSubSchedRefID =
			getTenderSubSchedRefID();

		gdfTenderSubSchedDetailsCacheModel.tenderItemNumber =
			getTenderItemNumber();

		gdfTenderSubSchedDetailsCacheModel.scheduleNumber = getScheduleNumber();

		gdfTenderSubSchedDetailsCacheModel.gdfGenericCode = getGdfGenericCode();

		String gdfGenericCode =
			gdfTenderSubSchedDetailsCacheModel.gdfGenericCode;

		if ((gdfGenericCode != null) && (gdfGenericCode.length() == 0)) {
			gdfTenderSubSchedDetailsCacheModel.gdfGenericCode = null;
		}

		gdfTenderSubSchedDetailsCacheModel.tenderReferenceNumber =
			getTenderReferenceNumber();

		String tenderReferenceNumber =
			gdfTenderSubSchedDetailsCacheModel.tenderReferenceNumber;

		if ((tenderReferenceNumber != null) &&
			(tenderReferenceNumber.length() == 0)) {

			gdfTenderSubSchedDetailsCacheModel.tenderReferenceNumber = null;
		}

		gdfTenderSubSchedDetailsCacheModel.scheduleName = getScheduleName();

		String scheduleName = gdfTenderSubSchedDetailsCacheModel.scheduleName;

		if ((scheduleName != null) && (scheduleName.length() == 0)) {
			gdfTenderSubSchedDetailsCacheModel.scheduleName = null;
		}

		gdfTenderSubSchedDetailsCacheModel.patientTarget = getPatientTarget();

		String patientTarget = gdfTenderSubSchedDetailsCacheModel.patientTarget;

		if ((patientTarget != null) && (patientTarget.length() == 0)) {
			gdfTenderSubSchedDetailsCacheModel.patientTarget = null;
		}

		gdfTenderSubSchedDetailsCacheModel.tenderItemRefID =
			getTenderItemRefID();

		gdfTenderSubSchedDetailsCacheModel.userId = getUserId();

		gdfTenderSubSchedDetailsCacheModel.userName = getUserName();

		String userName = gdfTenderSubSchedDetailsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			gdfTenderSubSchedDetailsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			gdfTenderSubSchedDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			gdfTenderSubSchedDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			gdfTenderSubSchedDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			gdfTenderSubSchedDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return gdfTenderSubSchedDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GDFTenderSubSchedDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GDFTenderSubSchedDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubSchedDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((GDFTenderSubSchedDetails)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GDFTenderSubSchedDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GDFTenderSubSchedDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GDFTenderSubSchedDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((GDFTenderSubSchedDetails)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, GDFTenderSubSchedDetails>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _tenderSubSchedRefID;
	private long _originalTenderSubSchedRefID;
	private boolean _setOriginalTenderSubSchedRefID;
	private long _tenderItemNumber;
	private long _originalTenderItemNumber;
	private boolean _setOriginalTenderItemNumber;
	private long _scheduleNumber;
	private long _originalScheduleNumber;
	private boolean _setOriginalScheduleNumber;
	private String _gdfGenericCode;
	private String _originalGdfGenericCode;
	private String _tenderReferenceNumber;
	private String _originalTenderReferenceNumber;
	private String _scheduleName;
	private String _patientTarget;
	private long _tenderItemRefID;
	private long _originalTenderItemRefID;
	private boolean _setOriginalTenderItemRefID;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private GDFTenderSubSchedDetails _escapedModel;

}