/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model.impl;

import com.gdf.technical.bids.model.GDFTenderSubmissionDetails;
import com.gdf.technical.bids.service.GDFTenderSubmissionDetailsLocalServiceUtil;

/**
 * The extended model base implementation for the GDFTenderSubmissionDetails service. Represents a row in the &quot;PRT_GDFTender_Subm_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GDFTenderSubmissionDetailsImpl}.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderSubmissionDetailsImpl
 * @see GDFTenderSubmissionDetails
 * @generated
 */
public abstract class GDFTenderSubmissionDetailsBaseImpl
	extends GDFTenderSubmissionDetailsModelImpl
	implements GDFTenderSubmissionDetails {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gdf tender submission details model instance should use the <code>GDFTenderSubmissionDetails</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GDFTenderSubmissionDetailsLocalServiceUtil.
				addGDFTenderSubmissionDetails(this);
		}
		else {
			GDFTenderSubmissionDetailsLocalServiceUtil.
				updateGDFTenderSubmissionDetails(this);
		}
	}

}