/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GDFTenderDetails service. Represents a row in the &quot;PRT_GDF_Tender_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.gdf.technical.bids.model.impl.GDFTenderDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.gdf.technical.bids.model.impl.GDFTenderDetailsImpl</code>.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderDetails
 * @generated
 */
@ProviderType
public interface GDFTenderDetailsModel extends BaseModel<GDFTenderDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gdf tender details model instance should use the {@link GDFTenderDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this gdf tender details.
	 *
	 * @return the primary key of this gdf tender details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gdf tender details.
	 *
	 * @param primaryKey the primary key of this gdf tender details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tender ref ID of this gdf tender details.
	 *
	 * @return the tender ref ID of this gdf tender details
	 */
	public long getTenderRefID();

	/**
	 * Sets the tender ref ID of this gdf tender details.
	 *
	 * @param tenderRefID the tender ref ID of this gdf tender details
	 */
	public void setTenderRefID(long tenderRefID);

	/**
	 * Returns the product category of this gdf tender details.
	 *
	 * @return the product category of this gdf tender details
	 */
	@AutoEscape
	public String getProductCategory();

	/**
	 * Sets the product category of this gdf tender details.
	 *
	 * @param productCategory the product category of this gdf tender details
	 */
	public void setProductCategory(String productCategory);

	/**
	 * Returns the tender reference number of this gdf tender details.
	 *
	 * @return the tender reference number of this gdf tender details
	 */
	@AutoEscape
	public String getTenderReferenceNumber();

	/**
	 * Sets the tender reference number of this gdf tender details.
	 *
	 * @param tenderReferenceNumber the tender reference number of this gdf tender details
	 */
	public void setTenderReferenceNumber(String tenderReferenceNumber);

	/**
	 * Returns the title of this gdf tender details.
	 *
	 * @return the title of this gdf tender details
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this gdf tender details.
	 *
	 * @param title the title of this gdf tender details
	 */
	public void setTitle(String title);

	/**
	 * Returns the publication date of this gdf tender details.
	 *
	 * @return the publication date of this gdf tender details
	 */
	public Date getPublicationDate();

	/**
	 * Sets the publication date of this gdf tender details.
	 *
	 * @param publicationDate the publication date of this gdf tender details
	 */
	public void setPublicationDate(Date publicationDate);

	/**
	 * Returns the deadline for tech bids sub of this gdf tender details.
	 *
	 * @return the deadline for tech bids sub of this gdf tender details
	 */
	public Date getDeadlineForTechBidsSub();

	/**
	 * Sets the deadline for tech bids sub of this gdf tender details.
	 *
	 * @param deadlineForTechBidsSub the deadline for tech bids sub of this gdf tender details
	 */
	public void setDeadlineForTechBidsSub(Date deadlineForTechBidsSub);

	/**
	 * Returns the method of this gdf tender details.
	 *
	 * @return the method of this gdf tender details
	 */
	@AutoEscape
	public String getMethod();

	/**
	 * Sets the method of this gdf tender details.
	 *
	 * @param method the method of this gdf tender details
	 */
	public void setMethod(String method);

	/**
	 * Returns the tender status of this gdf tender details.
	 *
	 * @return the tender status of this gdf tender details
	 */
	@AutoEscape
	public String getTenderStatus();

	/**
	 * Sets the tender status of this gdf tender details.
	 *
	 * @param tenderStatus the tender status of this gdf tender details
	 */
	public void setTenderStatus(String tenderStatus);

	/**
	 * Returns the deadline time for tech bids sub of this gdf tender details.
	 *
	 * @return the deadline time for tech bids sub of this gdf tender details
	 */
	public Date getDeadlineTimeForTechBidsSub();

	/**
	 * Sets the deadline time for tech bids sub of this gdf tender details.
	 *
	 * @param deadlineTimeForTechBidsSub the deadline time for tech bids sub of this gdf tender details
	 */
	public void setDeadlineTimeForTechBidsSub(Date deadlineTimeForTechBidsSub);

	/**
	 * Returns the user ID of this gdf tender details.
	 *
	 * @return the user ID of this gdf tender details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this gdf tender details.
	 *
	 * @param userId the user ID of this gdf tender details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this gdf tender details.
	 *
	 * @return the user uuid of this gdf tender details
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this gdf tender details.
	 *
	 * @param userUuid the user uuid of this gdf tender details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this gdf tender details.
	 *
	 * @return the user name of this gdf tender details
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this gdf tender details.
	 *
	 * @param userName the user name of this gdf tender details
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this gdf tender details.
	 *
	 * @return the create date of this gdf tender details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this gdf tender details.
	 *
	 * @param createDate the create date of this gdf tender details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this gdf tender details.
	 *
	 * @return the modified date of this gdf tender details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this gdf tender details.
	 *
	 * @param modifiedDate the modified date of this gdf tender details
	 */
	public void setModifiedDate(Date modifiedDate);

}