/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GDFTenderSubmissionDetails service. Represents a row in the &quot;PRT_GDFTender_Subm_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.gdf.technical.bids.model.impl.GDFTenderSubmissionDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.gdf.technical.bids.model.impl.GDFTenderSubmissionDetailsImpl</code>.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderSubmissionDetails
 * @generated
 */
@ProviderType
public interface GDFTenderSubmissionDetailsModel
	extends BaseModel<GDFTenderSubmissionDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gdf tender submission details model instance should use the {@link GDFTenderSubmissionDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this gdf tender submission details.
	 *
	 * @return the primary key of this gdf tender submission details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gdf tender submission details.
	 *
	 * @param primaryKey the primary key of this gdf tender submission details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tender sub ref ID of this gdf tender submission details.
	 *
	 * @return the tender sub ref ID of this gdf tender submission details
	 */
	public long getTenderSubRefID();

	/**
	 * Sets the tender sub ref ID of this gdf tender submission details.
	 *
	 * @param tenderSubRefID the tender sub ref ID of this gdf tender submission details
	 */
	public void setTenderSubRefID(long tenderSubRefID);

	/**
	 * Returns the tender reference number of this gdf tender submission details.
	 *
	 * @return the tender reference number of this gdf tender submission details
	 */
	@AutoEscape
	public String getTenderReferenceNumber();

	/**
	 * Sets the tender reference number of this gdf tender submission details.
	 *
	 * @param tenderReferenceNumber the tender reference number of this gdf tender submission details
	 */
	public void setTenderReferenceNumber(String tenderReferenceNumber);

	/**
	 * Returns the copy of reg cert of this gdf tender submission details.
	 *
	 * @return the copy of reg cert of this gdf tender submission details
	 */
	@AutoEscape
	public String getCopyOfRegCert();

	/**
	 * Sets the copy of reg cert of this gdf tender submission details.
	 *
	 * @param copyOfRegCert the copy of reg cert of this gdf tender submission details
	 */
	public void setCopyOfRegCert(String copyOfRegCert);

	/**
	 * Returns the supplier name of this gdf tender submission details.
	 *
	 * @return the supplier name of this gdf tender submission details
	 */
	@AutoEscape
	public String getSupplierName();

	/**
	 * Sets the supplier name of this gdf tender submission details.
	 *
	 * @param supplierName the supplier name of this gdf tender submission details
	 */
	public void setSupplierName(String supplierName);

	/**
	 * Returns the name of auth repr of this gdf tender submission details.
	 *
	 * @return the name of auth repr of this gdf tender submission details
	 */
	@AutoEscape
	public String getNameOfAuthRepr();

	/**
	 * Sets the name of auth repr of this gdf tender submission details.
	 *
	 * @param nameOfAuthRepr the name of auth repr of this gdf tender submission details
	 */
	public void setNameOfAuthRepr(String nameOfAuthRepr);

	/**
	 * Returns the supplier title of this gdf tender submission details.
	 *
	 * @return the supplier title of this gdf tender submission details
	 */
	@AutoEscape
	public String getSupplierTitle();

	/**
	 * Sets the supplier title of this gdf tender submission details.
	 *
	 * @param supplierTitle the supplier title of this gdf tender submission details
	 */
	public void setSupplierTitle(String supplierTitle);

	/**
	 * Returns the supplier email address of this gdf tender submission details.
	 *
	 * @return the supplier email address of this gdf tender submission details
	 */
	@AutoEscape
	public String getSupplierEmailAddress();

	/**
	 * Sets the supplier email address of this gdf tender submission details.
	 *
	 * @param supplierEmailAddress the supplier email address of this gdf tender submission details
	 */
	public void setSupplierEmailAddress(String supplierEmailAddress);

	/**
	 * Returns the supplier telephone number of this gdf tender submission details.
	 *
	 * @return the supplier telephone number of this gdf tender submission details
	 */
	@AutoEscape
	public String getSupplierTelephoneNumber();

	/**
	 * Sets the supplier telephone number of this gdf tender submission details.
	 *
	 * @param supplierTelephoneNumber the supplier telephone number of this gdf tender submission details
	 */
	public void setSupplierTelephoneNumber(String supplierTelephoneNumber);

	/**
	 * Returns the tender submission status of this gdf tender submission details.
	 *
	 * @return the tender submission status of this gdf tender submission details
	 */
	@AutoEscape
	public String getTenderSubmissionStatus();

	/**
	 * Sets the tender submission status of this gdf tender submission details.
	 *
	 * @param tenderSubmissionStatus the tender submission status of this gdf tender submission details
	 */
	public void setTenderSubmissionStatus(String tenderSubmissionStatus);

	/**
	 * Returns the supplier ID of this gdf tender submission details.
	 *
	 * @return the supplier ID of this gdf tender submission details
	 */
	public long getSupplierId();

	/**
	 * Sets the supplier ID of this gdf tender submission details.
	 *
	 * @param supplierId the supplier ID of this gdf tender submission details
	 */
	public void setSupplierId(long supplierId);

	/**
	 * Returns the user name of this gdf tender submission details.
	 *
	 * @return the user name of this gdf tender submission details
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this gdf tender submission details.
	 *
	 * @param userName the user name of this gdf tender submission details
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this gdf tender submission details.
	 *
	 * @return the create date of this gdf tender submission details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this gdf tender submission details.
	 *
	 * @param createDate the create date of this gdf tender submission details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this gdf tender submission details.
	 *
	 * @return the modified date of this gdf tender submission details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this gdf tender submission details.
	 *
	 * @param modifiedDate the modified date of this gdf tender submission details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the submitted date of this gdf tender submission details.
	 *
	 * @return the submitted date of this gdf tender submission details
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this gdf tender submission details.
	 *
	 * @param submittedDate the submitted date of this gdf tender submission details
	 */
	public void setSubmittedDate(Date submittedDate);

}