/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GDFTenderSubFPPMatDetails service. Represents a row in the &quot;PRT_GDFTender_SubFPPMat_Det&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.gdf.technical.bids.model.impl.GDFTenderSubFPPMatDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.gdf.technical.bids.model.impl.GDFTenderSubFPPMatDetailsImpl</code>.
 * </p>
 *
 * @author KS61374
 * @see GDFTenderSubFPPMatDetails
 * @generated
 */
@ProviderType
public interface GDFTenderSubFPPMatDetailsModel
	extends BaseModel<GDFTenderSubFPPMatDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gdf tender sub fpp mat details model instance should use the {@link GDFTenderSubFPPMatDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this gdf tender sub fpp mat details.
	 *
	 * @return the primary key of this gdf tender sub fpp mat details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gdf tender sub fpp mat details.
	 *
	 * @param primaryKey the primary key of this gdf tender sub fpp mat details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tender item mat ref ID of this gdf tender sub fpp mat details.
	 *
	 * @return the tender item mat ref ID of this gdf tender sub fpp mat details
	 */
	public long getTenderItemMatRefID();

	/**
	 * Sets the tender item mat ref ID of this gdf tender sub fpp mat details.
	 *
	 * @param tenderItemMatRefID the tender item mat ref ID of this gdf tender sub fpp mat details
	 */
	public void setTenderItemMatRefID(long tenderItemMatRefID);

	/**
	 * Returns the schedule number of this gdf tender sub fpp mat details.
	 *
	 * @return the schedule number of this gdf tender sub fpp mat details
	 */
	public long getScheduleNumber();

	/**
	 * Sets the schedule number of this gdf tender sub fpp mat details.
	 *
	 * @param scheduleNumber the schedule number of this gdf tender sub fpp mat details
	 */
	public void setScheduleNumber(long scheduleNumber);

	/**
	 * Returns the gdf generic code of this gdf tender sub fpp mat details.
	 *
	 * @return the gdf generic code of this gdf tender sub fpp mat details
	 */
	@AutoEscape
	public String getGdfGenericCode();

	/**
	 * Sets the gdf generic code of this gdf tender sub fpp mat details.
	 *
	 * @param gdfGenericCode the gdf generic code of this gdf tender sub fpp mat details
	 */
	public void setGdfGenericCode(String gdfGenericCode);

	/**
	 * Returns the tender reference number of this gdf tender sub fpp mat details.
	 *
	 * @return the tender reference number of this gdf tender sub fpp mat details
	 */
	@AutoEscape
	public String getTenderReferenceNumber();

	/**
	 * Sets the tender reference number of this gdf tender sub fpp mat details.
	 *
	 * @param tenderReferenceNumber the tender reference number of this gdf tender sub fpp mat details
	 */
	public void setTenderReferenceNumber(String tenderReferenceNumber);

	/**
	 * Returns the dosage form of this gdf tender sub fpp mat details.
	 *
	 * @return the dosage form of this gdf tender sub fpp mat details
	 */
	@AutoEscape
	public String getDosageForm();

	/**
	 * Sets the dosage form of this gdf tender sub fpp mat details.
	 *
	 * @param dosageForm the dosage form of this gdf tender sub fpp mat details
	 */
	public void setDosageForm(String dosageForm);

	/**
	 * Returns the no prim package units of this gdf tender sub fpp mat details.
	 *
	 * @return the no prim package units of this gdf tender sub fpp mat details
	 */
	public long getNoPrimPackageUnits();

	/**
	 * Sets the no prim package units of this gdf tender sub fpp mat details.
	 *
	 * @param noPrimPackageUnits the no prim package units of this gdf tender sub fpp mat details
	 */
	public void setNoPrimPackageUnits(long noPrimPackageUnits);

	/**
	 * Returns the no sec package units of this gdf tender sub fpp mat details.
	 *
	 * @return the no sec package units of this gdf tender sub fpp mat details
	 */
	public long getNoSecPackageUnits();

	/**
	 * Sets the no sec package units of this gdf tender sub fpp mat details.
	 *
	 * @param noSecPackageUnits the no sec package units of this gdf tender sub fpp mat details
	 */
	public void setNoSecPackageUnits(long noSecPackageUnits);

	/**
	 * Returns the gdf fpp mart appr status of this gdf tender sub fpp mat details.
	 *
	 * @return the gdf fpp mart appr status of this gdf tender sub fpp mat details
	 */
	@AutoEscape
	public String getGdfFppMartApprStatus();

	/**
	 * Sets the gdf fpp mart appr status of this gdf tender sub fpp mat details.
	 *
	 * @param gdfFppMartApprStatus the gdf fpp mart appr status of this gdf tender sub fpp mat details
	 */
	public void setGdfFppMartApprStatus(String gdfFppMartApprStatus);

	/**
	 * Returns the fpp selected status of this gdf tender sub fpp mat details.
	 *
	 * @return the fpp selected status of this gdf tender sub fpp mat details
	 */
	public boolean getFppSelectedStatus();

	/**
	 * Returns <code>true</code> if this gdf tender sub fpp mat details is fpp selected status.
	 *
	 * @return <code>true</code> if this gdf tender sub fpp mat details is fpp selected status; <code>false</code> otherwise
	 */
	public boolean isFppSelectedStatus();

	/**
	 * Sets whether this gdf tender sub fpp mat details is fpp selected status.
	 *
	 * @param fppSelectedStatus the fpp selected status of this gdf tender sub fpp mat details
	 */
	public void setFppSelectedStatus(boolean fppSelectedStatus);

	/**
	 * Returns the fpp market ID of this gdf tender sub fpp mat details.
	 *
	 * @return the fpp market ID of this gdf tender sub fpp mat details
	 */
	public long getFppMarketID();

	/**
	 * Sets the fpp market ID of this gdf tender sub fpp mat details.
	 *
	 * @param fppMarketID the fpp market ID of this gdf tender sub fpp mat details
	 */
	public void setFppMarketID(long fppMarketID);

	/**
	 * Returns the tender item ref ID of this gdf tender sub fpp mat details.
	 *
	 * @return the tender item ref ID of this gdf tender sub fpp mat details
	 */
	public long getTenderItemRefID();

	/**
	 * Sets the tender item ref ID of this gdf tender sub fpp mat details.
	 *
	 * @param tenderItemRefID the tender item ref ID of this gdf tender sub fpp mat details
	 */
	public void setTenderItemRefID(long tenderItemRefID);

	/**
	 * Returns the user ID of this gdf tender sub fpp mat details.
	 *
	 * @return the user ID of this gdf tender sub fpp mat details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this gdf tender sub fpp mat details.
	 *
	 * @param userId the user ID of this gdf tender sub fpp mat details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this gdf tender sub fpp mat details.
	 *
	 * @return the user uuid of this gdf tender sub fpp mat details
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this gdf tender sub fpp mat details.
	 *
	 * @param userUuid the user uuid of this gdf tender sub fpp mat details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this gdf tender sub fpp mat details.
	 *
	 * @return the user name of this gdf tender sub fpp mat details
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this gdf tender sub fpp mat details.
	 *
	 * @param userName the user name of this gdf tender sub fpp mat details
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this gdf tender sub fpp mat details.
	 *
	 * @return the create date of this gdf tender sub fpp mat details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this gdf tender sub fpp mat details.
	 *
	 * @param createDate the create date of this gdf tender sub fpp mat details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this gdf tender sub fpp mat details.
	 *
	 * @return the modified date of this gdf tender sub fpp mat details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this gdf tender sub fpp mat details.
	 *
	 * @param modifiedDate the modified date of this gdf tender sub fpp mat details
	 */
	public void setModifiedDate(Date modifiedDate);

}