/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.service.base;

import com.gdf.technical.bids.model.GDFTenderSubmissionDetails;
import com.gdf.technical.bids.service.GDFTenderSubmissionDetailsLocalService;
import com.gdf.technical.bids.service.persistence.GDFTenderDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderScheduleItemPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubFPPMatDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubFPPRegDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubSchedDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubmissionDetailsPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the gdf tender submission details local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.gdf.technical.bids.service.impl.GDFTenderSubmissionDetailsLocalServiceImpl}.
 * </p>
 *
 * @author KS61374
 * @see com.gdf.technical.bids.service.impl.GDFTenderSubmissionDetailsLocalServiceImpl
 * @generated
 */
public abstract class GDFTenderSubmissionDetailsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GDFTenderSubmissionDetailsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GDFTenderSubmissionDetailsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.gdf.technical.bids.service.GDFTenderSubmissionDetailsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the gdf tender submission details to the database. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderSubmissionDetails the gdf tender submission details
	 * @return the gdf tender submission details that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GDFTenderSubmissionDetails addGDFTenderSubmissionDetails(
		GDFTenderSubmissionDetails gdfTenderSubmissionDetails) {

		gdfTenderSubmissionDetails.setNew(true);

		return gdfTenderSubmissionDetailsPersistence.update(
			gdfTenderSubmissionDetails);
	}

	/**
	 * Creates a new gdf tender submission details with the primary key. Does not add the gdf tender submission details to the database.
	 *
	 * @param tenderSubRefID the primary key for the new gdf tender submission details
	 * @return the new gdf tender submission details
	 */
	@Override
	@Transactional(enabled = false)
	public GDFTenderSubmissionDetails createGDFTenderSubmissionDetails(
		long tenderSubRefID) {

		return gdfTenderSubmissionDetailsPersistence.create(tenderSubRefID);
	}

	/**
	 * Deletes the gdf tender submission details with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tenderSubRefID the primary key of the gdf tender submission details
	 * @return the gdf tender submission details that was removed
	 * @throws PortalException if a gdf tender submission details with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GDFTenderSubmissionDetails deleteGDFTenderSubmissionDetails(
			long tenderSubRefID)
		throws PortalException {

		return gdfTenderSubmissionDetailsPersistence.remove(tenderSubRefID);
	}

	/**
	 * Deletes the gdf tender submission details from the database. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderSubmissionDetails the gdf tender submission details
	 * @return the gdf tender submission details that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GDFTenderSubmissionDetails deleteGDFTenderSubmissionDetails(
		GDFTenderSubmissionDetails gdfTenderSubmissionDetails) {

		return gdfTenderSubmissionDetailsPersistence.remove(
			gdfTenderSubmissionDetails);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			GDFTenderSubmissionDetails.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return gdfTenderSubmissionDetailsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderSubmissionDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return gdfTenderSubmissionDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderSubmissionDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return gdfTenderSubmissionDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return gdfTenderSubmissionDetailsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return gdfTenderSubmissionDetailsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public GDFTenderSubmissionDetails fetchGDFTenderSubmissionDetails(
		long tenderSubRefID) {

		return gdfTenderSubmissionDetailsPersistence.fetchByPrimaryKey(
			tenderSubRefID);
	}

	/**
	 * Returns the gdf tender submission details with the primary key.
	 *
	 * @param tenderSubRefID the primary key of the gdf tender submission details
	 * @return the gdf tender submission details
	 * @throws PortalException if a gdf tender submission details with the primary key could not be found
	 */
	@Override
	public GDFTenderSubmissionDetails getGDFTenderSubmissionDetails(
			long tenderSubRefID)
		throws PortalException {

		return gdfTenderSubmissionDetailsPersistence.findByPrimaryKey(
			tenderSubRefID);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			gdfTenderSubmissionDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GDFTenderSubmissionDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tenderSubRefID");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			gdfTenderSubmissionDetailsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			GDFTenderSubmissionDetails.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"tenderSubRefID");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			gdfTenderSubmissionDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GDFTenderSubmissionDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tenderSubRefID");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return gdfTenderSubmissionDetailsLocalService.
			deleteGDFTenderSubmissionDetails(
				(GDFTenderSubmissionDetails)persistedModel);
	}

	public BasePersistence<GDFTenderSubmissionDetails> getBasePersistence() {
		return gdfTenderSubmissionDetailsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gdfTenderSubmissionDetailsPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the gdf tender submission detailses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderSubmissionDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of gdf tender submission detailses
	 * @param end the upper bound of the range of gdf tender submission detailses (not inclusive)
	 * @return the range of gdf tender submission detailses
	 */
	@Override
	public List<GDFTenderSubmissionDetails> getGDFTenderSubmissionDetailses(
		int start, int end) {

		return gdfTenderSubmissionDetailsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of gdf tender submission detailses.
	 *
	 * @return the number of gdf tender submission detailses
	 */
	@Override
	public int getGDFTenderSubmissionDetailsesCount() {
		return gdfTenderSubmissionDetailsPersistence.countAll();
	}

	/**
	 * Updates the gdf tender submission details in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderSubmissionDetails the gdf tender submission details
	 * @return the gdf tender submission details that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GDFTenderSubmissionDetails updateGDFTenderSubmissionDetails(
		GDFTenderSubmissionDetails gdfTenderSubmissionDetails) {

		return gdfTenderSubmissionDetailsPersistence.update(
			gdfTenderSubmissionDetails);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GDFTenderSubmissionDetailsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		gdfTenderSubmissionDetailsLocalService =
			(GDFTenderSubmissionDetailsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GDFTenderSubmissionDetailsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return GDFTenderSubmissionDetails.class;
	}

	protected String getModelClassName() {
		return GDFTenderSubmissionDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				gdfTenderSubmissionDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected GDFTenderDetailsPersistence gdfTenderDetailsPersistence;

	@Reference
	protected GDFTenderScheduleItemPersistence gdfTenderScheduleItemPersistence;

	@Reference
	protected GDFTenderSubFPPMatDetailsPersistence
		gdfTenderSubFPPMatDetailsPersistence;

	@Reference
	protected GDFTenderSubFPPRegDetailsPersistence
		gdfTenderSubFPPRegDetailsPersistence;

	protected GDFTenderSubmissionDetailsLocalService
		gdfTenderSubmissionDetailsLocalService;

	@Reference
	protected GDFTenderSubmissionDetailsPersistence
		gdfTenderSubmissionDetailsPersistence;

	@Reference
	protected GDFTenderSubSchedDetailsPersistence
		gdfTenderSubSchedDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}