/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gdf.technical.bids.service.base;

import com.gdf.technical.bids.model.GDFTenderDetails;
import com.gdf.technical.bids.service.GDFTenderDetailsLocalService;
import com.gdf.technical.bids.service.persistence.GDFTenderDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderScheduleItemPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubFPPMatDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubFPPRegDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubSchedDetailsPersistence;
import com.gdf.technical.bids.service.persistence.GDFTenderSubmissionDetailsPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the gdf tender details local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.gdf.technical.bids.service.impl.GDFTenderDetailsLocalServiceImpl}.
 * </p>
 *
 * @author KS61374
 * @see com.gdf.technical.bids.service.impl.GDFTenderDetailsLocalServiceImpl
 * @generated
 */
public abstract class GDFTenderDetailsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GDFTenderDetailsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GDFTenderDetailsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.gdf.technical.bids.service.GDFTenderDetailsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the gdf tender details to the database. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderDetails the gdf tender details
	 * @return the gdf tender details that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GDFTenderDetails addGDFTenderDetails(
		GDFTenderDetails gdfTenderDetails) {

		gdfTenderDetails.setNew(true);

		return gdfTenderDetailsPersistence.update(gdfTenderDetails);
	}

	/**
	 * Creates a new gdf tender details with the primary key. Does not add the gdf tender details to the database.
	 *
	 * @param tenderRefID the primary key for the new gdf tender details
	 * @return the new gdf tender details
	 */
	@Override
	@Transactional(enabled = false)
	public GDFTenderDetails createGDFTenderDetails(long tenderRefID) {
		return gdfTenderDetailsPersistence.create(tenderRefID);
	}

	/**
	 * Deletes the gdf tender details with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tenderRefID the primary key of the gdf tender details
	 * @return the gdf tender details that was removed
	 * @throws PortalException if a gdf tender details with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GDFTenderDetails deleteGDFTenderDetails(long tenderRefID)
		throws PortalException {

		return gdfTenderDetailsPersistence.remove(tenderRefID);
	}

	/**
	 * Deletes the gdf tender details from the database. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderDetails the gdf tender details
	 * @return the gdf tender details that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GDFTenderDetails deleteGDFTenderDetails(
		GDFTenderDetails gdfTenderDetails) {

		return gdfTenderDetailsPersistence.remove(gdfTenderDetails);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			GDFTenderDetails.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return gdfTenderDetailsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return gdfTenderDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return gdfTenderDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return gdfTenderDetailsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return gdfTenderDetailsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public GDFTenderDetails fetchGDFTenderDetails(long tenderRefID) {
		return gdfTenderDetailsPersistence.fetchByPrimaryKey(tenderRefID);
	}

	/**
	 * Returns the gdf tender details with the primary key.
	 *
	 * @param tenderRefID the primary key of the gdf tender details
	 * @return the gdf tender details
	 * @throws PortalException if a gdf tender details with the primary key could not be found
	 */
	@Override
	public GDFTenderDetails getGDFTenderDetails(long tenderRefID)
		throws PortalException {

		return gdfTenderDetailsPersistence.findByPrimaryKey(tenderRefID);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			gdfTenderDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GDFTenderDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tenderRefID");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			gdfTenderDetailsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(GDFTenderDetails.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"tenderRefID");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			gdfTenderDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GDFTenderDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tenderRefID");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return gdfTenderDetailsLocalService.deleteGDFTenderDetails(
			(GDFTenderDetails)persistedModel);
	}

	public BasePersistence<GDFTenderDetails> getBasePersistence() {
		return gdfTenderDetailsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gdfTenderDetailsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the gdf tender detailses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.gdf.technical.bids.model.impl.GDFTenderDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of gdf tender detailses
	 * @param end the upper bound of the range of gdf tender detailses (not inclusive)
	 * @return the range of gdf tender detailses
	 */
	@Override
	public List<GDFTenderDetails> getGDFTenderDetailses(int start, int end) {
		return gdfTenderDetailsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of gdf tender detailses.
	 *
	 * @return the number of gdf tender detailses
	 */
	@Override
	public int getGDFTenderDetailsesCount() {
		return gdfTenderDetailsPersistence.countAll();
	}

	/**
	 * Updates the gdf tender details in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param gdfTenderDetails the gdf tender details
	 * @return the gdf tender details that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GDFTenderDetails updateGDFTenderDetails(
		GDFTenderDetails gdfTenderDetails) {

		return gdfTenderDetailsPersistence.update(gdfTenderDetails);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GDFTenderDetailsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		gdfTenderDetailsLocalService = (GDFTenderDetailsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GDFTenderDetailsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return GDFTenderDetails.class;
	}

	protected String getModelClassName() {
		return GDFTenderDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = gdfTenderDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected GDFTenderDetailsLocalService gdfTenderDetailsLocalService;

	@Reference
	protected GDFTenderDetailsPersistence gdfTenderDetailsPersistence;

	@Reference
	protected GDFTenderScheduleItemPersistence gdfTenderScheduleItemPersistence;

	@Reference
	protected GDFTenderSubFPPMatDetailsPersistence
		gdfTenderSubFPPMatDetailsPersistence;

	@Reference
	protected GDFTenderSubFPPRegDetailsPersistence
		gdfTenderSubFPPRegDetailsPersistence;

	@Reference
	protected GDFTenderSubmissionDetailsPersistence
		gdfTenderSubmissionDetailsPersistence;

	@Reference
	protected GDFTenderSubSchedDetailsPersistence
		gdfTenderSubSchedDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}